name: Kronshop
version: 0.1-Beta
main: Market\Main
api: 5.0.0
author: Kronnosy
description:   
  Kronshop is an advanced marketplace system that allows players to easily buy and sell in-game items.
  Players can check prices, add all inventory items at once, and trade quickly and securely.
  Admins can fully customize the market settings for a balanced economy experience.


commands:
  market:
    description: View or manage market commands
    usage: "/market [list|buy|sell|price|addall]"
    permission: market.use
    aliases: [m, pazar]

permissions:
  market.use:
    description: Allows players to use market commands.
    default: true
  market.admin:
    description: Grants access to market admin commands.
    default: op

